#NOTES: 
#joint_state_controller key contains configuration for the controllers that drivers should use 
#controller_list contains configuration MoveIt needs to send trajectories to robot driver
#generic_hw_loop and hardware_interface - keys contain configuration for a ros_control_boilerplate "simulator" setup
#generic_hw_loop params loaded via - rosparam_shortcuts::get()
#R1 = right fin: first actuator
hardware_interface:
  joints:
    - R1_base_link_to_2nd_link
    - R1_2nd_link_to_3rd_link
  control_mode: 0 #0: only pos, 1: pos and wave membrane

#generic control loop params
generic_hw_control_loop:
  loop_hz: 40
  cycle_time_error_threshold: 1.0
  
# http://wiki.ros.org/joint_trajectory_controller
#Group Position Controller
#send a MultiArray message to control each joint
# velocity/position interface
stingray_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: 
    - R1_base_link_to_2nd_link
    - R1_2nd_link_to_3rd_link
  state_publish_rate: 50
  cmd_vel_timeout: 0.25

wave_model:
  #advertise_left: " "
  advertise_right: " "
  # 0: only pos, 1: pos and wave membrane
  robot_fin_controller_mode: 0
  #0: one frequency mode, 1: goal position mode
  robot_fin_state_mode: 0

